name: TF testing

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to trigger on'
        required: true
        type: string
      paths:
        description: 'Paths to trigger on'
        required: false
        type: string
        default: 'TF/**'

jobs:
  tf_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download code from current repo branch (checkout)
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
        
      # CODE COMPOSITION CHECK   
      - name: Terraform formating check (terraform fmt)
        run: terraform fmt -check ${{ inputs.path }}

      - name: TF code validation (terraform validate)
        run: terraform validate ${{ inputs.path }}
           
      - name: TFLint installation
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init
      - name: SCA with TFLint
        run: tflint ${{ inputs.path }}

      # SECURITY CHECK
      - name: tfsec setup
        run: |
          go install github.com/aquasecurity/tfsec/cmd/tfsec@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: tfsec scanning
        run: tfsec ${{ inputs.path }}
        
      - name: Checkov setup & scanning
        run: |
          pip install -U checkov
          checkov -d ${{ inputs.path }}
